### ISSUE TITLE
metrics fail parsing by prometheus 2.34.0 on windows

### ISSUE THREAD

**Issue by chi-ham** [ThomasMaul/Prometheus_4D_Exporter#1] opened 2022-04-25 21:25 UTC
I've installed the component in our application and verified that it starts the "Prometheus_4D_Exporter" web server and answers http get requests to "/metrics" on our configured port. Prometheus 2.34.0 is installed on another windows server and promtool verifies the prometheus.yml file with the additions for our test server. promtool.exe does not verify the metrics when an http get is piped with the command "check metrics". 

curl -s http://citi-test.artic.edu:{ourPort}/metrics | promtool check metrics
error while linting: text format parsing error in line 1: invalid metric name

Environment is 4D Server 19r2 running as a service on Windows Server 2019.

**Comment by ThomasMaul** [comment] 2022-04-26 05:10
Looks like the metrics file contains an invisible character or something. Did you modified it?
Download it (via curl or any browser) and save the file to disk. Use promtool again - and open the file with a text editor (Notepad++ or BBedit) to check for invisible chars. If that don't help, please send me that file by mail...

**Comment by ThomasMaul** [comment] 2022-04-26 08:03
ah, a typical error is when the file metrics.html is transferred between computers the format might get modified.
Double check that it is in LF format, not CRLF.
Prometheus only accepts files with char 10, not with char 13 or char13+10
Wrong line breaks stops parsing in line 1, even if that line is empty...

**Comment by chi-ham** [comment] 2022-04-26 21:26
Checked the metrics.shtml file originally downloaded with BBEdit of LF format and replaced the copy in the component of the host application. Better results, but still a parsing issue. Possibly the parser has changed with a newer version of prometheus.

curl -s [http://citi-test.artic.edu:{ourPort}/metrics](http://citi-test.artic.edu:%7BourPort%7D/metrics) | promtool check metrics
error while linting: text format parsing error in line 32: expected integer as timestamp, got ""

Hard to tell if it looking for a value that is not there or actually found two quotes. Of course line 32 is from the generated response not the source shtml.

This was what got returned on line 32. There are a series of space characters following '149'.
`FourD_Measures_WriteDisk_bytes{table="Preferences_Old", type="data"} 149           `

It looks like line 32 was generated in this section and was the only table generating this metric.
```
<!--#4DIF $measures.DB.tables#null--><!--#4DIF (num($writeBytes)#0)-->
# HELP FourD_Measures_WriteDisk_bytes Write from disk statistics per table
# TYPE FourD_Measures_WriteDisk_bytes gauge
<!--#4DEACH $table in $measures.DB.tables--><!--#4DIF ($measures.DB.tables[$table].diskWriteBytes#NULL)--><!--#4DCODE
$total:=$measures.DB.tables[$table].diskWriteBytes.history.query("time>:1";$history).sum("value")--><!--#4DIF ($total#0)-->
FourD_Measures_WriteDisk_bytes{table="<!--#4DTEXT $table-->", type="data"} <!--#4DTEXT $total--><!--4DENDIF--> <!--4DENDIF--><!--#4DENDEACH--><!--#4DENDIF--><!--#4DENDIF-->
```

**Comment by chi-ham** [comment] 2022-04-26 22:36
Have it working by removing a space between two of the  tags inside the for each loops. The space was being added for each table not included in the metric.

**Comment by ThomasMaul** [comment] 2022-04-27 06:10
ok, thanks for the feedback, I still could not reproduce. 
I tested with Prometheus 2.35.0 from 2022-04-20, the latest version as of today. So I close the issue

**Closed as completed by ThomasMaul** 2022-04-27 06:10 UTC
